# Generated by Django 4.2.7 on 2024-10-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_activities_selfemployed_selfemployedactivities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfemployed',
            name='INN',
            field=models.IntegerField(default='', max_length=100, verbose_name='ИНН'),
        ),
    ]
