# Generated by Django 4.2.7 on 2024-10-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_activities_selfemployed_selfemployedactivities_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selfemployedactivities',
            unique_together=set(),
        ),
    ]
