# Generated by Django 4.2.7 on 2024-10-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_selfemployed_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfemployed',
            name='INN',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='ИНН'),
        ),
    ]
