# Generated by Django 4.2.7 on 2024-10-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_selfemployed_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfemployed',
            name='INN',
            field=models.CharField(default='Отсутствует', max_length=100, verbose_name='ИНН'),
        ),
    ]
