# Generated by Django 4.2.7 on 2024-09-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
